export const MOCK_ITEMS = [
    {
        id: '1',
        name: 'Minimalist Beige Sofa',
        short_description: '3-Seater Living Room Sofa',
        full_description: 'Extremely comfortable 3-seater sofa in a warm beige fabric. Barely used, sat in a secondary living room. Cushions still hold their shape perfectly. Selling because I am moving to a smaller apartment.',
        price: 350000,
        status: 'available',
        condition_grade: 'New: Never opened',
        category: 'living_room',
        images: ['/images/sofa.png'],
        specs: { 'Brand': 'Custom Made', 'Material': 'Linen Blend Fabric', 'Color': 'Warm Beige', 'Dimensions': 'W: 220cm x D: 90cm x H: 85cm' },
        extras: ['3 matching throw pillows included'],
        updated_at: '2 Mins Ago'
    },
    {
        id: '2',
        name: 'ECM Espresso Machine',
        short_description: 'Stainless Steel Coffee Maker',
        full_description: 'Professional grade prosumer espresso machine. Features a dual boiler and PID temperature control. Has been backflushed regularly and only used with filtered water.',
        price: 1200000,
        status: 'negotiation',
        condition_grade: '9+: Preowned equipment that shows little to no signs of wear',
        category: 'kitchen',
        images: ['/images/coffee.png'],
        specs: { 'Brand': 'ECM', 'Model': 'Synchronika', 'Material': 'Stainless Steel', 'Boiler Type': 'Dual Boiler' },
        extras: ['Bottomless portafilter', 'Tamper', 'Milk frothing jug'],
        updated_at: '1 Hour Ago'
    },
    {
        id: '3',
        name: 'Samsung 27" Monitor',
        short_description: '4K UHD Display',
        full_description: 'Great 4K monitor for productivity and light gaming. Excellent color accuracy. Upgrading to a larger ultrawide.',
        price: 85000,
        status: 'sold',
        condition_grade: '9: Very good condition; overall looks clean but may have minor signs of use/surface marks',
        category: 'electronics',
        images: ['/images/monitor.png'],
        specs: { 'Resolution': '3840 x 2160', 'Refresh Rate': '60Hz', 'Panel Type': 'IPS' },
        extras: ['Power cable', 'HDMI cable'],
        updated_at: 'Yesterday'
    },
    {
        id: '4',
        name: 'Large Monstera Deliciosa',
        short_description: 'Healthy indoor plant with ceramic pot',
        full_description: 'Beautiful, large Monstera plant. Has been thriving in bright indirect light. Comes with a premium white ceramic planter and drainage saucer.',
        price: 15000,
        status: 'available',
        condition_grade: '10: Preowned equipment that looks good as new; no signs of wear',
        category: 'living_room',
        images: ['/images/plant.png'],
        specs: { 'Height': 'Approx 1.2m', 'Pot Material': 'Ceramic' },
        extras: [],
        updated_at: '2 Days Ago'
    },
    {
        id: '5',
        name: 'Ergonomic Office Chair',
        short_description: 'Fully adjustable desk chair',
        full_description: 'High-quality ergonomic chair with lumbar support, adjustable armrests, and seat depth adjustment. Perfect for WFH.',
        price: 150000,
        status: 'available',
        condition_grade: '8+: Shows moderate wear, scuffing or marks to finish',
        category: 'work_den',
        images: ['/images/sofa.png'], // Reusing placeholders
        specs: { 'Brand': 'Herman Miller (Replica)', 'Color': 'Black', 'Material': 'Mesh' },
        extras: [],
        updated_at: '3 Days Ago'
    },
    {
        id: '6',
        name: 'Solid Wood Dining Table',
        short_description: 'Seats up to 6 people',
        full_description: 'Beautiful solid oak dining table. Shows some signs of use with minor surface scratches but structural integrity is perfect.',
        price: 200000,
        status: 'available',
        condition_grade: '8: Well used-may exhibit "dings" or noticeable marks to finish',
        category: 'kitchen',
        images: ['/images/sofa.png'],
        specs: { 'Material': 'Oak Wood', 'Dimensions': '160cm x 90cm' },
        extras: [],
        updated_at: '4 Days Ago'
    },
    {
        id: '7',
        name: 'Apple MacBook Pro M1',
        short_description: '16GB RAM, 512GB SSD',
        full_description: 'M1 MacBook Pro in Space Gray. Battery health is at 89%. Works flawlessly.',
        price: 850000,
        status: 'negotiation',
        condition_grade: '9+: Preowned equipment that shows little to no signs of wear',
        category: 'electronics',
        images: ['/images/monitor.png'],
        specs: { 'Chip': 'Apple M1', 'RAM': '16GB', 'Storage': '512GB SSD', 'Year': '2020' },
        extras: ['Original charger', 'USB-C Cable', 'Leather sleeve'],
        updated_at: '1 Week Ago'
    },
    {
        id: '8',
        name: 'Le Creuset Dutch Oven',
        short_description: 'Classic Cast Iron Casserole',
        full_description: 'Iconic Le Creuset Dutch oven in volcanic orange. Used for baking bread and stews. Some staining inside but cooks perfectly.',
        price: 110000,
        status: 'available',
        condition_grade: '7: Shows considerable wear and above-average signs of use',
        category: 'kitchen',
        images: ['/images/coffee.png'],
        specs: { 'Brand': 'Le Creuset', 'Capacity': '5.3 Liters', 'Material': 'Enameled Cast Iron' },
        extras: [],
        updated_at: '1 Week Ago'
    },
    {
        id: '9',
        name: 'Nintendo Switch OLED',
        short_description: 'White Joy-Cons + Accessories',
        full_description: 'Switch OLED model. Screen has had a protector since day 1. Selling because I don\'t play it enough.',
        price: 280000,
        status: 'sold',
        condition_grade: '10: Preowned equipment that looks good as new; no signs of wear',
        category: 'electronics',
        images: ['/images/monitor.png'],
        specs: { 'Model': 'OLED', 'Color': 'White', 'Storage': '64GB' },
        extras: ['Carrying case', 'Dock', 'HDMI Cable', 'Zelda: Breath of the Wild'],
        updated_at: '1 Week Ago'
    },
    {
        id: '10',
        name: 'Vintage Persian Rug',
        short_description: 'Hand-knotted wool rug',
        full_description: 'Stunning vintage rug with deep reds and blues. Just professionally cleaned.',
        price: 450000,
        status: 'available',
        condition_grade: '9: Very good condition; overall looks clean but may have minor signs of use/surface marks',
        category: 'living_room',
        images: ['/images/plant.png'],
        specs: { 'Dimensions': '200cm x 300cm', 'Material': '100% Wool', 'Origin': 'Iran' },
        extras: ['Rug pad included'],
        updated_at: '2 Weeks Ago'
    },
    {
        id: '11',
        name: 'Dyson V11 Vacuum',
        short_description: 'Cordless stick vacuum',
        full_description: 'Powerful cordless vacuum. Battery still holds a good charge. Filters have been washed regularly.',
        price: 320000,
        status: 'available',
        condition_grade: '8+: Shows moderate wear, scuffing or marks to finish',
        category: 'electronics',
        images: ['/images/coffee.png'],
        specs: { 'Brand': 'Dyson', 'Model': 'V11 Absolute' },
        extras: ['Wall mount', 'Crevice tool', 'Motorized brush head'],
        updated_at: '2 Weeks Ago'
    },
    {
        id: '12',
        name: 'Queen Size Mattress',
        short_description: 'Memory foam mattress (Medium Firm)',
        full_description: 'Very comfortable memory foam mattress. Always used with a waterproof mattress protector. Clean and smoke-free home.',
        price: 180000,
        status: 'available',
        condition_grade: '9: Very good condition; overall looks clean but may have minor signs of use/surface marks',
        category: 'bedroom',
        images: ['/images/sofa.png'],
        specs: { 'Size': 'Queen (150x200cm)', 'Type': 'Memory Foam', 'Firmness': 'Medium Firm' },
        extras: [],
        updated_at: '2 Weeks Ago'
    }
];
